
public class ExceptionTest {

	public static void main(String[] args) {

		String str = null;
		int [] ary = new int [5];
		try { // 예외가 발생할지도 모르는 코드

			ary[5] = 10;
			str.toString();
			System.out.println("되나?");
			
		} catch (NullPointerException e) { // 예외 발생시에 처리 코드
			System.out.println(e.getMessage());
			System.out.println("객체생성하고 쓰라");
		}
	}
}
